#!/bin/bash

set -x

set -eo pipefail

# Download and unpack the operator binaries and config files.

mkdir -p $HOME/odev/bin
mkdir -p $HOME/odev/pkg

mkdir -p $HOME/odev/src/github.com/crunchydata/postgres-operator

curl -sL -o /tmp/postgres-operator.tar.gz https://github.com/CrunchyData/postgres-operator/releases/download/3.5.2/postgres-operator.3.5.2.tar.gz

cd $HOME/odev/src/github.com/crunchydata/postgres-operator

tar xzf /tmp/postgres-operator.tar.gz

cp -a pgo $HOME/odev/bin/pgo
cp -a expenv $HOME/odev/bin/expenv

rm /tmp/postgres-operator.tar.gz

# Setup user environment with environment variables and bash completion.

cat $HOME/.workshop/envvars >> /opt/app-root/etc/profile.d/postgres.sh
cat $HOME/.workshop/envvars >> $HOME/.bash_profile

echo 'export CO_APISERVER_URL=https://`kubectl get service postgres-operator -o=jsonpath="{.spec.clusterIP}"`:8443' >> $HOME/.bash_profile

cat examples/pgo-bash-completion >> $HOME/.bash_profile

# Fix up our own environment for executing remainder of commands.

. $HOME/.workshop/envvars

# Generate SSHD and API keys. These will be shared for all sessions.

. deploy/gen-sshd-keys.sh

. deploy/gen-api-keys.sh

# Set a username/password for accessing operator REST API.

echo "username:password" > $HOME/.pgouser

mv $HOME/workshop /opt/app-root/workshop

# Delete all non required files from the image
rm -rf Dockerfile README.md LICENSE
