#!/bin/bash

set -x

set -eo pipefail

# Download and unpack the operator binaries and config files.

mkdir -p $HOME/odev/bin
mkdir -p $HOME/odev/pkg
mkdir -p $HOME/jan/test

echo "export GOPATH=$HOME/go" >> ~/.bashrc
echo "export GOBIN=$GOPATH/bin" >> ~/.bashrc
echo "export PATH=\$PATH:\$GOROOT/bin:\$GOPATH/bin" >> ~/.bashrc
. ~/.bashrc

mkdir -p $GOPATH/bin
# install "dep"
curl -L https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -o $GOPATH/bin/dep

# install operator-sdk
curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.7.0/operator-sdk-v0.7.0-x86_64-linux-gnu -o $HOME/odev/bin/operator-sdk
chmod 755 $HOME/odev/bin/operator-sdk

$GOPATH/bin/dep

# setup git profile
git config --global user.email "operator-sdk@example.com"
git config --global user.name "OperatorSDK Lab"

# Setup user environment with environment variables and bash completion.

cat $HOME/.workshop/envvars >> /opt/app-root/etc/profile.d/operatorsdklab.sh
cat $HOME/.workshop/envvars >> $HOME/.bash_profile

echo 'export CO_APISERVER_URL=https://`kubectl get service postgres-operator -o=jsonpath="{.spec.clusterIP}"`:8443' >> $HOME/.bash_profile

# Fix up our own environment for executing remainder of commands.

. $HOME/.workshop/envvars

# TODO is the below relevant?
# Generate SSHD and API keys. These will be shared for all sessions.
# . deploy/gen-sshd-keys.sh
# . deploy/gen-api-keys.sh

mv $HOME/workshop /opt/app-root/workshop

# Delete all non required files from the image
rm -rf Dockerfile README.md LICENSE